export const refs = {
  home: document.querySelector('.js-nav-home-btn'),
  library: document.querySelector('.js-nav-library-btn'),
  logo: document.querySelector('.js-logo-btn'),
  watched: document.querySelector('.js-btn-watched'),
  queue: document.querySelector('.js-btn-queue'),
  librarySection: document.querySelector('.library'),
  form: document.querySelector('.form'),
  header: document.querySelector('.header'),
  btnOpenModalTeam: document.querySelector('.js-open-modal-team'),
  modalTeam: document.querySelector('.js-modal-team'),
  btnCloseModalTeam: document.querySelector('.js-close-modal-team'),
  formEl: document.querySelector('.form'),
  galleryEl: document.querySelector('.gallery__container'),
  errorEl: document.querySelector('.search-error'),
  errorImgEl: document.querySelector('.errorImg__container'),
  paginationContainer: document.getElementById('tui-pagination-container'),
  scrollToTopEl: document.querySelector('.scroll-to-top'),
  // filmCard: document.querySelector('.film-card'),
  // btnCloseModalFilm: document.querySelector('.modal-film__button-close'),
};
